name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "b2a94704b6ba44b1a4642914f64ec1f7" }
]

[triggers]
crons = [ ]
